// const specializationsConstants = [
//     "Abuse",
//     "Accessibility Concerns",
//     "Addiction",
//     "ADHD",
//     "Anger/Anger Management",
//     "Anti-Oppression Grief",
//     "Anxiety",
//     "ASD",
//     "Attachment Disorder",
//     "Behavioural Issues",
//     "BIPOC",
//     "Bipolar Disorder",
//     "Body Image Challenges",
//     "Borderline Personality Disorder",
//     "Boundaries",
//     "Burnout",
//     "Capacity Building",
//     "Career Development or Direction",
//     "Career Issues",
//     "Childhood Abuse/Neglect",
//     "Childhood Trauma",
//     "Codependency",
//     "Communication Issues",
//     "Couples",
//     "Cross-Cultural Consideration in Clinical Practice",
//     "Cultural Transitions",
//     "Custom Group Workshops for Organizations",
//     "Depression",
//     "Developing Positive Habits",
//     "Developmental Disabilities",
//     "Developmental Disorders",
//     "Dissociative Identity Disorder (DID)",
//     "Domestic Violence",
//     "Early Adulthood",
//     "Eating Disorders",
//     "Educational Psychology",
//     "Emotional Disturbance",
//     "Emotional Regulation/Resiliency",
//     "Empowerment",
//     "Existential Concern/Life Crises",
//     "Family Conflict",
//     "Family Dynamics/Conflict",
//     "Goal Attainment",
//     "Grief",
//     "Grief/Loss",
//     "Health",
//     "Health Care Professionals",
//     "High IQ",
//     "Homesickness",
//     "Identity Issues",
//     "Immigrant Experiences",
//     "Impulse Control Disorders",
//     "Infidelity",
//     "Intergenerational Trauma",
//     "LGBTQIA+",
//     "Life Changes",
//     "Life Coaching",
//     "Life Transitions",
//     "Loneliness",
//     "Low Motivation",
//     "Marginalization",
//     "Marital and Premarital",
//     "Medical Students",
//     "Men’s Issues",
//     "Mixed-Race",
//     "Mood Disorders",
//     "Multicultural Counselling",
//     "Negative Thinking Patterns",
//     "Neurodivergence",
//     "New Immigrant",
//     "Non-Binary",
//     "Nursing Students",
//     "Obsessive-Compulsive Disorder (OCD)",
//     "Oppositional Defiance",
//     "Oppression",
//     "Panic Disorder",
//     "Parent-Child Relationship",
//     "Parenting",
//     "Peer Relationships",
//     "Perfectionism",
//     "Personal Growth/Development",
//     "Personality Disorders",
//     "Post-Traumatic Stress Disorder (PTSD)",
//     "Pregnant and/or Postpartum Parents",
//     "Queer Issues",
//     "Racial Identity",
//     "Relationship Issues",
//     "Self-Harming",
//     "Self Esteem",
//     "Separation",
//     "Sexual Abuse",
//     "Sexuality",
//     "Spirituality",
//     "Stress Management/Stress",
//     "Students",
//     "Substance Use",
//     "Suicidal Ideation",
//     "Teen Violence",
//     "Trans",
//     "Trauma",
//     "Trauma and PTSD",
//     "Women’s Issues",
//     "Youth/Young Adults",
// ];
//
// export default specializationsConstants;